# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  repository_dispatch:
    types: [test_cucumber]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven      
      run: mvn clean compile -B package --file pom.xml 
    - name: generate auxiliary JSON for authenticating with Xray cloud and obtain token
      run: |
        cat cloud_auth.json.sample  | sed s/CLIENT_ID/${{ github.event.client_payload.clientId }}/g | sed s/CLIENT_SECRET/${{ github.event.client_payload.clientSecret }}/g > cloud_auth.json
        echo token=$(curl -H "Content-Type: application/json" -X POST --data @"cloud_auth.json" ${{ secrets.XRAYCLOUD_BASE_URL }}/api/v1/authenticate| tr -d '"') >> $GITHUB_ENV
    - name: Export Xray cucumber feature
      run: |
        rm -rf xray/features/*
        curl -H "Content-Type: application/json" -X GET -H "Authorization: Bearer ${{ env.token }}"  "${{ secrets.XRAYCLOUD_BASE_URL }}/api/v2/export/cucumber?keys=${{ github.event.client_payload.testkeys }}" --output xray/features.zip
        unzip xray/features.zip -f xray/features
    - name: Run tests
      run: |
        mvn test -Dcucumber.plugin="json:report.json" -Dcucumber.features="xray/features/"
        cat report.json
    
    - name: "Import results to Xray (cloud) using multipart endpoint"
      run: |
        cat test_exec.json
        curl -X POST -H "Authorization: Bearer ${{ env.token }}" -F info=@test_exec.json -F results=@"report.json" "${{ secrets.XRAYCLOUD_BASE_URL }}/api/v1/import/execution/cucumber/multipart"
